In [12]:
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
data = pd.read_excel('inputs/Pune Real Estate Data.xlsx')
data.head()

,Sr. No.,Location,Sub-Area,Propert Type,Property Area in Sq. Ft.,Price in lakhs,Price in Millions,Company Name,TownShip Name/ Society Name,Total TownShip Area in Acres,ClubHouse,School / University in Township,Hospital in TownShip,Mall in TownShip,Park / Jogging track,Swimming Pool,Gym,Description
0,1,"Pune, Maharashtra, India",Bavdhan,1 BHK,492,39,3.9,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Shapoorji Paloonji comunity located in the sub...
1,2,"Pune, Maharashtra, India",Bavdhan,2 BHK,774,65,6.5,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Township located near the lonavala hill...
2,3,"Pune, Maharashtra, India",Bavdhan,3 BHK,889,74,7.4,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Society is suitable for all aged group ...
3,4,"Pune, Maharashtra, India",Bavdhan,3 BHK Grand,1018,89,8.9,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha township are offering 3BHK grand prpoer...
4,5,"Pune, Maharashtra, India",Mahalunge,2BHK,743,74,7.4,Godrej Properties,Godrej Hills retreat,100.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,The area is a hub of prestigious schools like ...

In [9]:
# Extracting State and Country separately from the Location Column
data['City'] = data['Location'].apply(lambda x: x.split(',')[0].lower().strip())
data['State'] = data['Location'].apply(lambda x: x.split(',')[1].lower().strip())
data['Country'] = data['Location'].apply(lambda x: x.split(',')[2].lower().strip())
data.head(3)

,Sr. No.,Location,Sub-Area,Propert Type,Property Area in Sq. Ft.,Price in lakhs,Price in Millions,Company Name,TownShip Name/ Society Name,Total TownShip Area in Acres,...,School / University in Township,Hospital in TownShip,Mall in TownShip,Park / Jogging track,Swimming Pool,Gym,Description,City,State,Country
0,1,"Pune, Maharashtra, India",Bavdhan,1 BHK,492,39,3.9,Shapoorji Paloonji,Vanaha,1000.0,...,Yes,Yes,Yes,Yes,Yes,Yes,Shapoorji Paloonji comunity located in the sub...,pune,maharashtra,india
1,2,"Pune, Maharashtra, India",Bavdhan,2 BHK,774,65,6.5,Shapoorji Paloonji,Vanaha,1000.0,...,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Township located near the lonavala hill...,pune,maharashtra,india
2,3,"Pune, Maharashtra, India",Bavdhan,3 BHK,889,74,7.4,Shapoorji Paloonji,Vanaha,1000.0,...,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Society is suitable for all aged group ...,pune,maharashtra,india

In [10]:
data['Propert Type'].value_counts()

Propert Type
2bhk           56
3BHK           28
3bhk           19
2BHK           18
2 bhk          16
3 bhk          10
1BHK            9
1bhk            7
1 BHK           3
2bhk            3
2 bhk           2
3.5 bhk         2
3.5bhk          2
2.5 bhk         2
4 bhk           2
2.5 BHK         2
3 BHK           2
5BHK            2
2 BHK           1
3bhk            1
4.5bhk          1
1bhk            1
5 bhk           1
3+2bhk          1
2+2 bhk         1
3 BHK Grand     1
3 BHK           1
4BHK            1
6BHK            1
shop            1
1 bhk           1
3  bhk          1
4bhk            1
Name: count, dtype: int64

In [14]:
# Regex to match the numbers and create a separate column
numbers = re.compile(r"[-+]?(\d*\.\d+|\d+)") 
data['Property Type'] = data['Propert Type'].apply(lambda x: numbers.findall(x)[0] if len(numbers.findall(x)) > 0 else 0)

In [15]:
data['Sub-Area'].value_counts()

Sub-Area
Kharadi                     16
handewadi                   11
BT Kawade RD                10
Hinjewadi                    9
Ravet                        9
wadgaon sheri                9
hadapsar                     8
NIBM                         8
BANER                        7
pisoli                       6
kiwale                       6
vimannagar                   6
Akurdi                       6
Susgaon                      6
bavdhan budruk               6
bavdhan                      6
Karvanagar                   5
manjri                       5
Mahalunge                    5
Mundhwa                      5
dhanori                      4
Bavdhan                      4
mahalunge                    4
Balewadi                     4
tathawade                    4
KirkatWadi Sinhagad Road     3
baner                        3
Keshav Nagar                 3
ravet                        3
Undri                        2
mohammadwadi                 2
Koregaon Park                2
Baner                        2
lonavala                     2
magarpatta                   2
kayani nagar                 2
talegoan                     2
koregoan                     2
pimpri pune                  1
Name: count, dtype: int64

In [16]:
data['Sub-Area'] = data['Sub-Area'].apply(lambda x: x.lower().strip())

In [17]:
data['Company Name'].value_counts()

Company Name
Mantra Properties                29
kundan Spaces                    14
unique properties                11
Shapoorji Paloonji               10
jhala group                      10
Vijaya Laxmi Creations            9
Puraniks                          8
ravima ventures                   7
Lush Life                         6
vijaya Laxmi infrarealtors        6
VTP Reality                       6
Porwal & Anand Develkoper         6
nirman developers                 6
Oxy Buildcorp                     6
Kalpataru                         5
kohinoor group                    5
maha anand Pinnac associates      5
Urban Space Creator               5
SUPREME                           4
keystone landmark                 4
Wellwisher Apartments             3
Dolphin Group                     3
Bhaktamar Realities               3
proviso group                     3
venkatesh bhoomi construction     2
majestique landmarks              2
Calyx Spaces                      2
ANP CORP                          2
Waghvani Constructions            2
Porwal  Develkoper                2
Sukwani Associates                2
Godrej Properties                 2
sagitarius ecospaces llp          2
shroff developers                 2
ace constructions                 2
vasupujya corporation             2
Tejraaj Group                     2
Name: count, dtype: int64

In [18]:
data['Company Name'] = data['Company Name'].apply(lambda x: x.lower().strip())

In [19]:
data['TownShip Name/ Society Name'].value_counts()

TownShip Name/ Society Name
Mantra 29 Gold           13
Eternia 2.0               8
brookefield willows       6
newton homes              6
Oxy Beaumonde             6
k ville                   6
Sensorium                 6
Abitante Fiore            6
Satyam Shery              6
Parklane UrbanJoy         6
Satyam Serenity           6
Impero                    6
Mantra Sky Tower          6
Presidia                  6
unique legacy royale      5
River Dale Residency      5
Urban Skyline             5
oxy eterno                4
mahalunge riviera         4
Vanaha                    4
SUPREME ESTIA             4
tranquility annexe        3
Mantra Insignia           3
Sportsville               3
Dolphin Garima            3
kiarah terrazo            3
VTP Blue Water            3
jade residences           3
7Hills                    3
Satyam Shivam             3
lesiure Town              3
simplicity                3
Bhaktamar Residency       3
puraniks Sayama           2
Kalpataru Serenity        2
Atulya Kanhe              2
Rhythm county             2
TEJ ELEVIA                2
khush vista               2
Bliss Solitaire           2
Presidenta                2
Anutham                   2
Neco Beaumont             2
Godrej Hills retreat      2
aureta                    2
bluegrass residences      2
Infinity                  2
Mantra Monarch            2
Sukwani Aspire            2
OM Mangalam Chaitanya     2
VTP Cierra                2
ANP Universe              2
the work club             1
vtp solitaire             1
Name: count, dtype: int64